apis:
  - ignore
backends:
  - ignore
gateways:
 - ignore
diagnostics:
  - ignore
groups:
  - ignore
loggers:
  - ignore
namedValues:
  - ignore
products:
  - cicd-test
subscriptions:
  - ignore
tags:
  - ignore
policyFragments:
  - ignore
versionSets:
  - ignore
