apis:
  - git-test
backends:
  - ignore
gateways:
 - ignore
diagnostics:
  - ignore
groups:
  - ignore
loggers:
  - ignore
namedValues:
  - ignore
products:
  - ignore
subscriptions:
  - ignore
tags:
  - ignore
policyFragments:
  - ignore
